name: Deployment
on: 
  push:
    branches:
      - master
      - production

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache Yarn modules
        uses: actions/cache@v2
        id: cache-yarn-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-cache-yarn-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-yarn-modules-
            ${{ runner.os }}-

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile
      
      - name: Lint
        uses: mooyoul/tslint-actions@v1.1.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          pattern: '*.ts'

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache Yarn modules
        uses: actions/cache@v2
        id: cache-yarn-modules
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-cache-yarn-modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-cache-yarn-modules-
            ${{ runner.os }}-

      - name: Install Yarn dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: build/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v12.8.0
        with:
          args: deploy --only hosting --project ${{ secrets.CODEML_PROJECT_ID }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
